# Generated by Django 3.2.5 on 2021-07-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pims', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='container',
            name='is_partial',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1),
        ),
        migrations.AlterField(
            model_name='container',
            name='season',
            field=models.ManyToManyField(blank=True, to='pims.season'),
        ),
    ]
