# Generated by Django 3.2.5 on 2021-07-26 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pims', '0004_container_random_col'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='random_col',
        ),
        migrations.RemoveField(
            model_name='container',
            name='season',
        ),
    ]
