# Generated by Django 3.2.5 on 2021-07-26 05:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pims', '0005_auto_20210725_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='row_letter',
            field=models.CharField(default="A", max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='container',
            name='season',
            field=models.ManyToManyField(blank=True, to='pims.season'),
        ),
    ]
