# Generated by Django 3.2.5 on 2021-07-26 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pims', '0006_auto_20210725_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='column_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='container',
            name='row_letter',
            field=models.CharField(default='A', max_length=1),
        ),
    ]
