# Generated by Django 3.2.5 on 2021-07-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pims', '0007_auto_20210725_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='row_letter',
            field=models.CharField(max_length=1),
        ),
    ]
