# Generated by Django 3.2.5 on 2021-08-29 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pims', '0008_alter_container_row_letter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='container',
        ),
        migrations.AddField(
            model_name='container',
            name='items',
            field=models.ManyToManyField(to='pims.item'),
        ),
    ]
