# Generated by Django 3.2.11 on 2022-10-11 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pims', '0011_auto_20220522_1850'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='container',
            options={'ordering': ['location']},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='item_container',
            options={'ordering': ['-id'], 'verbose_name': 'Items in Container'},
        ),
        migrations.AlterField(
            model_name='container',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
