# Generated by Django 3.2.11 on 2023-01-08 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pims', '0012_auto_20221011_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='slug',
            field=models.SlugField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='season',
            name='slug',
            field=models.SlugField(max_length=25, null=True),
        ),
    ]
